name: PianoFromAbove build
on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/**
      - .gitignore
      - README.md
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
  queue: max

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Set up build tools
        shell: pwsh
        run: |
          choco upgrade directx-sdk nsis.portable -y
          $dxsdk = [Environment]::GetEnvironmentVariable("DXSDK_DIR","Machine")
          echo "DXSDK_DIR=$dxsdk" >> $env:GITHUB_ENV
          echo "VCToolsVersion=14.51.36231" >> $env:GITHUB_ENV

      - name: Verify build environment
        shell: pwsh
        run: |
          where.exe cl makensis
          "cl","makensis" | ForEach-Object { Get-Command $_ -ErrorAction Stop }
          cl
          makensis /VERSION

      - name: Build executable
        shell: pwsh
        working-directory: ./
        run: |
          cmd.exe /c "ci.bat"

      - name: Compare artifact build
        uses: KarbitsCode/artifact-comparer@43db522959d21d1bad41a884670eaa59035878fd
        with:
          artifact-name: windows-build
          path: Dist/
          artifact-subpath: Dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: windows-build
          compression-level: 9
          path: |
            Debug/
            Release/
            Dist/

      - name: Scan with VirusTotal
        uses: crazy-max/ghaction-virustotal@v5.0.0
        with:
          vt_api_key: ${{ secrets.VT_KEY }}
          files: |
            ./Debug/*.exe
            ./Release/*.exe
            ./Dist/*
